# Generated by Django 4.0.3 on 2022-06-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ombor',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='ombor',
            name='tel_raqam',
        ),
        migrations.AddField(
            model_name='ombor',
            name='dokon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ombor',
            name='tel',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ombor',
            name='ism',
            field=models.CharField(max_length=50),
        ),
    ]
